name: Base Guidelines Compliance

on:
  pull_request:
    branches: [main, develop]

jobs:
  compliance-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check code quality
        run: |
          npm run lint
          npm run type-check
          npm run test:coverage
      
      - name: Validate documentation structure
        run: |
          npm run docs:validate-structure
          npm run docs:validate-templates
      
      - name: Validate architecture compliance
        run: |
          npm run validate:architecture
          npm run validate:security
          npm run validate:performance
      
      - name: Generate compliance report
        run: npm run generate:compliance-report
        
      - name: Upload compliance report
        uses: actions/upload-artifact@v4
        with:
          name: compliance-report
          path: reports/compliance-report.html