name: Base Guidelines Compliance

on:
    pull_request:
        branches: [main, develop]
    push:
        branches: [main, develop]

permissions:
  contents: read
  actions: write
  pull-requests: write
  issues: write

jobs:
    compliance-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Critical error checks (blocking)
              run: npm run check:critical

            - name: Comprehensive project error check
              run: npm run check:errors

            - name: Validate documentation structure
              run: |
                  bash scripts/validate-docs-structure.sh
                  npm run lint:templates

            - name: Validate architecture compliance
              run: |
                  npm run lint:architecture
                  npm run lint:security
                  npm run lint:performance

            - name: Generate comprehensive compliance report
              run: npm run compliance:report

            - name: Upload compliance report
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: compliance-report
                  path: reports/
                  retention-days: 30
